### ISSUE TITLE
Use wsl1 not the wsl2 or you will have error code: 0x80370114

### ISSUE THREAD

**Issue by aierlma** [VsTechDev/Fedora-WSL#13]
In my case, I use wsl 2 first and I get error code 0x80370114. Then I run this 
`wsl --set-default-version 1`
Finally I can install fedora!
I think this might be helpful for others.

**Comment by vineelsai26** [comment]
Hi @aierlma checkout this issue https://github.com/microsoft/WSL/issues/4626 this might be a problem related to virtualization in your PC because I use WSL 2 without any problem and I don't recommend using WSL 1 because it's very slow 
![image](https://user-images.githubusercontent.com/52851879/213368609-d802c21c-15ba-4ba3-85c3-1c25f1fd4350.png)

**Comment by vineelsai26** [comment]
Great let me know if you face any other problems
